try:
    num = 15/5
    print(num)
except:
    print("Something went wrong")
finally:
    print("This is DOne")

# https://realpython.com/python-exceptions/
# https://docs.python.org/3/tutorial/errors.html